FROM rodrigocsmprojel/docker-ceedling

RUN apt-get update && apt-get install -y \
    bison \
    flex \
    gperf \
    lcov

ADD build.sh /opt/TestCov/

WORKDIR /opt/TestCov

CMD /bin/bash build.sh -g

