on: [push]

jobs:
  badge_job:
    runs-on: ubuntu-latest
    name: Testing BYOB
    steps:
      - id: date
        run: echo "##[set-output name=data;]$(date)"
      - id: machine
        run: echo "##[set-output name=data;]$(hostname)"
      - id: size
        run: echo "##[set-output name=50;]"
      - name: Set selected color
        run: echo '::set-env name=SELECTED_COLOR::green'
      - name: Get color
        run: echo 'The selected color is' $SELECTED_COLOR
      - name: Set cv
        run: echo '::set-output name={secrets.CODECOV_TOKEN}::{50}'
