on: [push]

jobs:
  badge_job:
    runs-on: ubuntu-latest
    name: Testing codecov
    steps:
      - id: date
        run: echo "##[set-output name=data;]$(date)"
      - id: machine
        run: echo "##[set-output name=data;]$(hostname)"
      - id: size
        run: echo "##[set-output name=data;]$(du -sh . | sed 's/[^0-9a-zA-Z]//g')"
      - name: Time badge
        uses: RubbaBoy/BYOB@v1.1.0
        with:
          NAME: time
          LABEL: 'Updated at'
          STATUS: ${{ steps.date.outputs.data }}
          COLOR: 00EEFF
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Machine Badge
        uses: RubbaBoy/BYOB@v1.1.0
        with:
          NAME: machine
          LABEL: 'Hostname'
          STATUS: ${{ steps.machine.outputs.data }}
          COLOR: FFC0CB
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Size Badge
        uses: RubbaBoy/BYOB@v1.1.0
        with:
          NAME: size
          LABEL: 'Repo Size'
          STATUS: ${{ steps.size.outputs.data }}
          COLOR: 00FF00
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
