on: [push]

jobs:
  badge_job:
    runs-on: ubuntu-latest
    name: Testing CV
    with:
        GITHUB_TOKEN: 60
    steps:
      - id: date
        run: echo "##[set-output name=data;]$(date)"
      - id: machine
        run: echo "##[set-output name=data;]$(hostname)"
      - id: size
        run: echo "##[set-output name=50;]"
      - name: Set selected color
        run: echo '::set-env name=SELECTED_COLOR::green'
      - name: Get color
        run: echo 'The selected color is' $SELECTED_COLOR
      - name: Set & Get cv
        run: echo '::set-output name={GITHUB_TOKEN}::50'
             echo 'The cv is' $GITHUB_TOKEN
