on: [push]

jobs:
  badge_job:
    runs-on: ubuntu-latest
    name: Testing BYOB
    steps:
      - id: date
        run: echo "##[set-output name=data;]$(date)"
      - id: machine
        run: echo "##[set-output name=data;]$(hostname)"
      - id: size
        run: echo "##[set-output name=50;]"
      - name: Size Badge
        uses: actions/checkout@v2
        env:
        echo "::set-env name=CV::55"
        with:
          NAME: size
          LABEL: 'Repo Size'
          STATUS: ${{ steps.size.outputs.data }}
          COLOR: 00FF00
          GITHUB_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          secrets.CODECOV_TOKEN: 45
