on: [push]

jobs:
  badge_job:
    runs-on: ubuntu-latest
    name: Testing BYOB
    steps:
      - id: date
        run: echo "##[set-output name=data;]$(date)"
      - id: machine
        run: echo "##[set-output name=data;]$(hostname)"
      - id: size
        run: echo "##[set-output name=50;]"
      - name: Size Badge
        uses: RubbaBoy/BYOB@v1.1.0
        with:
          NAME: size
          LABEL: 'Repo Size'
          STATUS: ${{ steps.size.outputs.data }}
          COLOR: 00FF00
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
