name: Code coverage comment on pr
on: 
  pull_request:

jobs:
  example:
    name: Code coverage comment
    runs-on: ubuntu-latest
    steps:
      - name: comment PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        depends_on: Development	  
        with:
          msg: "Check out this message!"
          check_for_duplicate_msg: false  # OPTIONAL


